//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MirrorMotion.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Detection : global::System.Configuration.ApplicationSettingsBase {
        
        private static Detection defaultInstance = ((Detection)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Detection())));
        
        public static Detection Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double GrippedSwipe_MainAxisMinDistance {
            get {
                return ((double)(this["GrippedSwipe_MainAxisMinDistance"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double GrippedSwipe_OtherAxesMaxDistance {
            get {
                return ((double)(this["GrippedSwipe_OtherAxesMaxDistance"]));
            }
            set {
                this["GrippedSwipe_OtherAxesMaxDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int ConsecutiveComplexGesture_MinPeriodBetweenGestures {
            get {
                return ((int)(this["ConsecutiveComplexGesture_MinPeriodBetweenGestures"]));
            }
            set {
                this["ConsecutiveComplexGesture_MinPeriodBetweenGestures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ConsecutiveComplexGesture_MaxPeriodBetweenGestures {
            get {
                return ((int)(this["ConsecutiveComplexGesture_MaxPeriodBetweenGestures"]));
            }
            set {
                this["ConsecutiveComplexGesture_MaxPeriodBetweenGestures"] = value;
            }
        }
    }
}
